University Campus Hour - Capstone Project 1
PrangonGhose/Capstone-Project---University-Campus-Hour pull request #1
Opened 2022-11-23 16:38 UTC by PrangonGhose

- The project has been made using personalized ideas but following [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) for colors, typography, and layout.
- The project is done in plane CSS. No CSS framework has been used for styling.
- Only **Home** and **About** page have been designed as per the requirement of the project.
- Each of the pages have been adopted for 2 different screen sizes - **Mobile** *768px wide* and **Desktop** *768px or wider* as per the requirement.
- Interactions (e.g., *Links* and *Mobile menu*) are put.
- Dynamic page (*Featured Clubs*) is created using JavaScript.
- Readme file has been adopted as per the requirements.

2022-11-23 17:36 UTC, Abenezer-Tilahun requested changes
Hi @PrangonGhose   , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional  README 
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [ ]  As stated the project requirement you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. it's one of the project requirement you must fulfill for to get approval for project.
![Capture](https://user-images.githubusercontent.com/93598189/203611774-010112a5-1ddb-4a3a-8b1c-4f244f5b63a3.PNG)

_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 17:36 UTC, Abenezer-Tilahun commented on about.html
> +    <p class="rights"><i class="fa fa-copyright"></i>2021. All rights reserved</p>
- [ ]  As stated the project requirement The pages should look almost identical to the original design. So Kindly aligned the   "logo"  the `left` and "text" aligned to the `right` and adjust background color of the footer Just like the [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 

The Design Guidelines Look likes this 

![Capture](https://user-images.githubusercontent.com/93598189/203609151-e05a101f-18e7-4d88-993d-f2abcfe076ce.PNG)


Your Project Design Look likes this 

![Capture](https://user-images.githubusercontent.com/93598189/203607832-90b9e9a1-ad8b-43ae-bb39-d9d1054e3e13.PNG)

2022-11-23 17:36 UTC, Abenezer-Tilahun commented on index.html
> +    <p class="rights"><i class="fa fa-copyright"></i>2021. All rights reserved</p>
- [ ]  As stated the project requirement The pages should look almost identical to the original design. So Kindly aligned the   "logo"  the `left` and "text" aligned to the `right` Just like the [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 

The Design Guidelines Look likes this 

![Capture](https://user-images.githubusercontent.com/93598189/203607647-f2adee5b-e2fd-4d76-9298-210e7e7840a9.PNG)

Your Project Design Look likes this 

![Capture](https://user-images.githubusercontent.com/93598189/203607832-90b9e9a1-ad8b-43ae-bb39-d9d1054e3e13.PNG)

2022-11-23 17:36 UTC, Abenezer-Tilahun commented on about.html
> +    </ul>
- [ ] Kindly add "Home" link at the "About page" to  possible to navigate between the pages, there's a link from Home page to About page and the opposite too.

![Capture](https://user-images.githubusercontent.com/93598189/203608718-a1693730-c980-4ecf-9cda-6b8be89e5aec.PNG)

2022-11-23 17:36 UTC, Abenezer-Tilahun commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Kindly I recommend you to update your new [README template](https://github.com/microverseinc/readme-template) and All main headers from the README template should be present in a yours repo. But customize according to your project and please Make sure that you added the section "Future Features", including 1-3 potential features to be added.

2022-11-23 20:26 UTC, PrangonGhose commented
## Corrections after first review:
- Contact section is fully optimized as per the design guidelines in both about.html and index.html.
- README.md file has been changed as per the new template and future features are added.
- Presentation of the project can be found [here](https://www.loom.com/share/151a84b791384da683db56873ea48a41).

2022-11-23 21:17 UTC, Favourezeugwa requested changes
## STATUS: REQUIRES CHANGES ⚠️ 🚥 ♻️ 
Hi @PrangonGhose , 

Great work on making the changes requested by @Abenezer-Tilahun, your previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


![woman so close](https://user-images.githubusercontent.com/99246359/203647496-9b9a1265-5ceb-4823-9898-2e9f01949ff7.gif)

 ## Highlights 💯 
- No Linter errors ✔️ 
- Professional Readme file ✔️ 
- Good commit messages ✔️ 
- Descriptive PR ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 21:17 UTC, Favourezeugwa commented on index.html
> +  </header>
- Currently, I think the header of your mobile version currently contains the top dark bar and a bottom white bar that is only meant to be shown on your desktop screen. Apparently, from the Behance design, you only need just the **hamburger menu** on the **top right**.

Here is what I mean 👇🏽 
| Your mobile header  |Behance mobile header |
| :---:   | :---: | 
|![badmob](https://user-images.githubusercontent.com/99246359/203646395-524e560b-8f08-4e81-ac6d-8fc396147ed6.PNG)  |![goodmob](https://user-images.githubusercontent.com/99246359/203646486-1d00daf6-7132-4b2d-8211-4cae6881c7f2.PNG)  |

- Why don't we refactor your mobile header to look just like Behance? 🌸 
You can simply hide them on mobile and show them in your desktop version(using media query)

2022-11-24 06:42 UTC, PrangonGhose commented
## Corrections after second review:
- The position of hamburger icon has been optimized in the mobile version according to the design guidelines.

2022-11-24 07:04 UTC, Bondok6 approved these changes
## Hi @PrangonGhose 🙋‍♂️, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

- Great job implementing the changes provided by the previous reviewers 💯🎉

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-11-24 07:52 UTC, merged